#!/data/data/com.termux/files/usr/bin/bash
url=$1
opt="youtube-dl,ffmpeg,wget,spotdl,youtube-dl(audio),exit"
echo $opt
res=$(termux-dialog radio -t "Select Option" -v $opt)
echo $res
pik=$(echo ${res} | grep -Po "(?<=xt\": \")\w+")
ind=$(echo ${res} | grep -Po "(?<=ex\": )\d+")

case $ind in
  0)  # youtube-dl
    [ ! -d "./storage/downloads/youtube-dl" ] && mkdir "./storage/downloads/youtube-dl"
    youtube-dl c -i "$url" --cookies ~/cookies -o "./storage/download/youtube-dl/%(title)s.%(ext)s"
    ;;
  1)  # ffmpeg
    name=$(termux-dialog text -t "Output Filename" | grep -Po "(?<=xt\": \")[^\"]+")
    echo $name
    ffmpeg -i "$url" -c copy -bsf:a aac_adtstoasc ./storage/downloads/"$name"
    ;;
  2)  # wget
    wget -P "./storage/downloads/" -c --mirror  --recursive --no-clobber  --page-requisites --html-extension --convert-links -e robots=off --restrict-file-names=windows --no-parent "$url"
    ;;
  3)  # spot-dl
    [ ! -d "./storage/downloads/spotdl" ] && mkdir "./storage/downloads/spotdl"
    test -f  "./.spotdl_playlist"  && rm "./.spotdl_playlist.txt"
    test -f  "./.spotdl_album"  && rm "./.spotdl_album.txt"
    [[ $url == *"track"* ]] && spotdl --output-file "./storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --song "$url" -q best --output-ext flac
    [[ $url == *"playlist"* ]] && spotdl --playlist "$url" --write-to  "./.spotdl_playlist.txt"  && spotdl --output-file "./storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "./.spotdl_playlist.txt" -q best --output-ext flac && rm -f "./.spotdl_playlist.txt"
    [[ $url == *"album"* ]] && spotdl --album "$url" --write-to  "./.spotdl_album.txt" && spotdl --output-file "./storage/downloads/spotdl/{artist} - {track-name}.{output-ext}" --list "./.spotdl_album.txt" -q best --output-ext flac && rm -f "./.spotdl_album.txt"
    ;;
  4) # youtube-dl (audio)
    [ ! -d "./storage/downloads/youtube-dl" ] && mkdir "./storage/downloads/youtube-dl"
    youtube-dl -x --embed-thumbnail --audio-format mp3 -c -i "$url" --cookies  ~/cookies -o "./storage/downloads/youtube-dl/%(title)s.%(ext)s"
    ;;
  5) # exit
    exit 1
    ;;
esac
read
exit 0
