#!/bin/bash
clear
url=$1
echo "All-in-one Download Script for Termux"
echo "-------------------------------------"
echo "1: Download with youtube-dl"
echo "2: Download with ffmpeg(m3u8/m3u)"
echo "3: Download with wget (recursive)"
echo "Default: Download with youtube-dl"
read n
if [ "$n" == '2' ]; then
echo "Output Filename:"
read name
ffmpeg -i "$url" -c copy -bsf:a aac_adtstoasc ./storage/downloads/"$name"
.
else
if [ "$n" == '3' ]; then
wget -P "./storage/downloads/" -c --recursive --no-clobber  --page-requisites --html-extension --convert-links --restrict-file-names=windows --no-parent "$url" 
.
else
[ ! -d "./storage/downloads/youtube-dl" ] && mkdir "./storage/downloads/youtube-dl"
fi 
youtube-dl -f bestvideo+bestaudio -c -i "$url" --cookies  ~/cookies -o "./storage/downloads/youtube-dl/%(title)s.%(ext)s"
.
fi
fi
